name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
        cache: "yarn"
    - run: yarn
    - run: yarn build
    - run: yarn lint
    - run: yarn test
    - run: yarn build:cli
    - run: yarn scs help
    - name: minified file
      run: cat testOut/test.min.scs
    - name: prettified
      run: cat testOut/test.pretty.scs
    - name: parsed
      run: cat testOut/test.ignore.json
    - name: exec output
      run: cat testOut/test.exec.json
    - name: import test
      run: cat testOut/test.fs.exec.json
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: testoutput
        path: testOut
